print ('Ola usuario informe os dados solicitados!!')
name = input('Qual é o seu nome?')
dia = input ('Dia: ')
mes = input ('Mes: ')
ano = input ('Ano: ')
print (f'Olá {name} voce nasceu em {dia} de {mes} de {ano}!!')